# Generated by Django 5.0.3 on 2024-03-26 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='Ismi')),
                ('lastname', models.CharField(max_length=25, verbose_name='Familiyasi')),
                ('surname', models.CharField(max_length=25, verbose_name='Otasining ismi')),
                ('kaf', models.CharField(choices=[('Metematika - Informatika', 'Matematika - Informatika'), ('Fizika', 'Fizika'), ("Sana'tshunoslik", "Sana'tshunoslik"), ('Jismoniy madaniyat', 'Jismoniy madaniyat'), ('Tabiy fanlar', 'Tabiy fanlar'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Rus tili va Qozoq tillari filialogiyasi', 'Rus tili va Qozoq tillari filialogiyasi'), ('Tibbiyot', 'Tibbiyot'), ("Maktabgacha va boshlang'ich ta'lim", "Maktabgacha va boshlang'ich ta'lim"), ('Tarix', 'Tarix'), ('O‘zbek tili va adabiyoti fakulteti', 'O‘zbek tili va adabiyoti fakulteti')], default=None, max_length=155, verbose_name='Fakulteti')),
                ('ilimiy_darajasi', models.CharField(max_length=255, verbose_name="Ma'lumoti")),
                ('user_lavozimi', models.CharField(max_length=255, verbose_name='Lavozimi')),
                ('tel', models.IntegerField(verbose_name='Telefon raqami')),
                ('image', models.ImageField(upload_to='user_logo/')),
                ('mail', models.CharField(max_length=250, verbose_name='Mail')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
