# Generated by Django 5.0.3 on 2025-06-23 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoshqaMasala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Masala sarlavhasi')),
                ('description', models.TextField(blank=True, verbose_name='Masala tavsifi')),
            ],
            options={
                'verbose_name': 'Boshqa masala',
                'verbose_name_plural': 'Boshqa masalalar',
            },
        ),
        migrations.CreateModel(
            name='IlmiyUnvon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255, verbose_name='Nomzod (F.I.Sh)')),
                ('title', models.CharField(max_length=255, verbose_name='Beriladigan ilmiy unvon')),
                ('title_code', models.CharField(max_length=255, verbose_name='Ilmiy unvon shifri')),
            ],
            options={
                'verbose_name': 'Ilmiy Unvon uchun nomzod',
                'verbose_name_plural': 'Ilmiy Unvon uchun nomzodlar',
            },
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Kafedra nomi')),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedralar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kengash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Kengash nomi')),
            ],
            options={
                'verbose_name': 'Kengash',
                'verbose_name_plural': 'Kengashlar',
            },
        ),
        migrations.CreateModel(
            name='Lavozim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Lavozim nomi')),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Saylov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Masalan, 'Fizika-matematika fakulteti dekanligi uchun saylov'", max_length=255, verbose_name='Saylov sarlavhasi')),
                ('lavozim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.lavozim', verbose_name='Saylov lavozimi')),
            ],
            options={
                'verbose_name': 'Saylov',
                'verbose_name_plural': 'Saylovlar',
            },
        ),
        migrations.CreateModel(
            name='Byulleten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Byulleten sarlavhasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ovoz berish uchun ochiqmi?')),
                ('boshqa_masalalar', models.ManyToManyField(blank=True, related_name='byulletenlar', to='professors.boshqamasala', verbose_name='Boshqa masalalar')),
                ('unvonlar', models.ManyToManyField(blank=True, related_name='byulletenlar', to='professors.ilmiyunvon', verbose_name='Ilmiy unvonlar')),
                ('kengash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byulletenlar', to='professors.kengash')),
                ('saylovlar', models.ManyToManyField(blank=True, related_name='byulletenlar', to='professors.saylov', verbose_name='Saylovlar')),
            ],
            options={
                'verbose_name': 'Byulleten',
                'verbose_name_plural': 'Byulletenlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tanlov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255, verbose_name='Nomzod (F.I.Sh)')),
                ('saylov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomzodlar', to='professors.saylov', verbose_name='Saylov')),
            ],
            options={
                'verbose_name': 'Saylov nomzodi',
                'verbose_name_plural': 'Saylov nomzodlari',
                'ordering': ['candidate_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100, verbose_name='Otasining ismi')),
                ('academic_degree', models.CharField(max_length=255, verbose_name='Ilmiy darajasi')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozimi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Rasmi')),
                ('kafedra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.kafedra', verbose_name='Kafedrasi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi Profili',
                'verbose_name_plural': 'Foydalanuvchi Profillari',
            },
        ),
        migrations.CreateModel(
            name='SaylovVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saylov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='professors.saylov')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saylov_votes', to=settings.AUTH_USER_MODEL)),
                ('chosen_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_votes', to='professors.tanlov', verbose_name='Tanlangan nomzod')),
            ],
            options={
                'verbose_name': 'Saylov ovozi',
                'verbose_name_plural': 'Saylov ovozlari',
                'unique_together': {('user', 'saylov')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovoz', models.CharField(choices=[('ha', 'Ha'), ('yoq', "Yo'q"), ('betaraf', 'Betaraf')], max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Standart Ovoz',
                'verbose_name_plural': 'Standart Ovozlar',
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
