# Generated by Django 5.0.3 on 2024-07-24 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanlov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism Familiya sharif')),
                ('kaf', models.CharField(choices=[('Umumiy pedagogika va psixologiya', 'Umumiy pedagogika va psixologiya'), ('Maktabgacha ta’lim', 'Maktabgacha ta’lim'), ('Boshlang‘ich ta’lim', 'Boshlang‘ich ta’lim'), ('Pedagogika va psixologiya', 'Pedagogika va psixologiya'), ('Musiqa ta’limi', 'Musiqa ta’limi'), ('Tasviriy san’at va muhandislik grafikasi', 'Tasviriy san’at va muhandislik grafikasi'), ('Biologiya', 'Biologiya'), ('Kimyo', 'Kimyo'), ('Geografiya va iqtisodiy bilim asoslari', 'Geografiya va iqtisodiy bilim asoslari'), ('Matematika', 'Matematika'), ('Informatika', 'Informatika'), ('Fizika va astronomiya', 'Fizika va astronomiya'), ('Texnologik ta’lim', 'Texnologik ta’lim'), ('O‘zbek tilshunosligi', 'O‘zbek tilshunosligi'), ('O‘zbek tili va adabiyoti', 'O‘zbek tili va adabiyoti'), ('Tarix', 'Tarix'), ('Milliy g‘oya, ma’naviyat asoslari va huquq ta’limi', 'Milliy g‘oya, ma’naviyat asoslari va huquq ta’limi'), ('Ijtimoiy fanlar', 'Ijtimoiy fanlar'), ('Jismoni madaniyat', 'Jismoni madaniyat'), ('Sport turlarini o‘qitish metodikasi', 'Sport turlarini o‘qitish metodikasi'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Ingliz tili amaliy kursi', 'Ingliz tili amaliy kursi'), ('Fakultetlararo chet tillar', 'Fakultetlararo chet tillar'), ('Rus tili va adabiyoti', 'Rus tili va adabiyoti'), ('Qozoq tili va adabiyoti', 'Qozoq tili va adabiyoti'), ('Umumiy tibbiy fanlar', 'Umumiy tibbiy fanlar')], default=None, max_length=155, verbose_name='Kafedrasi')),
                ('scientific_title', models.CharField(choices=[('kafedra mudiri', 'kafedra mudiri'), ('kafedra professori', 'kafedra professori'), ('kafedra dotsenti', 'kafedra dotsenti'), ('kafedra katta o‘qituvchisi', 'kafedra katta o‘qituvchisi'), ('kafedra o‘qituvchisi lavozimi', 'kafedra o‘qituvchisi lavozimi')], max_length=255, verbose_name='Lavozimni tanlang')),
            ],
            options={
                'verbose_name': 'Tanlov',
                'verbose_name_plural': 'Tanlovlar',
            },
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Ovoz Berish', 'verbose_name_plural': 'Ovoz Berishlar'},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='scientific_title',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='unvon',
        ),
        migrations.AddField(
            model_name='ilmiyunvon',
            name='unvon_shifr',
            field=models.CharField(default=1, max_length=255, verbose_name='Ilmiy Unvon Shifri'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='ovoz',
            field=models.CharField(choices=[('Xa', 'Xa'), ('yoq', 'Yoq'), ('betaraf', 'Betaraf')], default=1, max_length=10, verbose_name='Ovoz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ilmiyunvon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ilmiyunvon',
            name='kaf',
            field=models.CharField(choices=[('Umumiy pedagogika va psixologiya', 'Umumiy pedagogika va psixologiya'), ('Maktabgacha ta’lim', 'Maktabgacha ta’lim'), ('Boshlang‘ich ta’lim', 'Boshlang‘ich ta’lim'), ('Pedagogika va psixologiya', 'Pedagogika va psixologiya'), ('Musiqa ta’limi', 'Musiqa ta’limi'), ('Tasviriy san’at va muhandislik grafikasi', 'Tasviriy san’at va muhandislik grafikasi'), ('Biologiya', 'Biologiya'), ('Kimyo', 'Kimyo'), ('Geografiya va iqtisodiy bilim asoslari', 'Geografiya va iqtisodiy bilim asoslari'), ('Matematika', 'Matematika'), ('Informatika', 'Informatika'), ('Fizika va astronomiya', 'Fizika va astronomiya'), ('Texnologik ta’lim', 'Texnologik ta’lim'), ('O‘zbek tilshunosligi', 'O‘zbek tilshunosligi'), ('O‘zbek tili va adabiyoti', 'O‘zbek tili va adabiyoti'), ('Tarix', 'Tarix'), ('Milliy g‘oya, ma’naviyat asoslari va huquq ta’limi', 'Milliy g‘oya, ma’naviyat asoslari va huquq ta’limi'), ('Ijtimoiy fanlar', 'Ijtimoiy fanlar'), ('Jismoni madaniyat', 'Jismoni madaniyat'), ('Sport turlarini o‘qitish metodikasi', 'Sport turlarini o‘qitish metodikasi'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Ingliz tili amaliy kursi', 'Ingliz tili amaliy kursi'), ('Fakultetlararo chet tillar', 'Fakultetlararo chet tillar'), ('Rus tili va adabiyoti', 'Rus tili va adabiyoti'), ('Qozoq tili va adabiyoti', 'Qozoq tili va adabiyoti'), ('Umumiy tibbiy fanlar', 'Umumiy tibbiy fanlar')], default=None, max_length=155, verbose_name='Kafedrasi'),
        ),
        migrations.AlterField(
            model_name='usercreate',
            name='kaf',
            field=models.CharField(choices=[('Umumiy pedagogika va psixologiya', 'Umumiy pedagogika va psixologiya'), ('Maktabgacha ta’lim', 'Maktabgacha ta’lim'), ('Boshlang‘ich ta’lim', 'Boshlang‘ich ta’lim'), ('Pedagogika va psixologiya', 'Pedagogika va psixologiya'), ('Musiqa ta’limi', 'Musiqa ta’limi'), ('Tasviriy san’at va muhandislik grafikasi', 'Tasviriy san’at va muhandislik grafikasi'), ('Biologiya', 'Biologiya'), ('Kimyo', 'Kimyo'), ('Geografiya va iqtisodiy bilim asoslari', 'Geografiya va iqtisodiy bilim asoslari'), ('Matematika', 'Matematika'), ('Informatika', 'Informatika'), ('Fizika va astronomiya', 'Fizika va astronomiya'), ('Texnologik ta’lim', 'Texnologik ta’lim'), ('O‘zbek tilshunosligi', 'O‘zbek tilshunosligi'), ('O‘zbek tili va adabiyoti', 'O‘zbek tili va adabiyoti'), ('Tarix', 'Tarix'), ('Milliy g‘oya, ma’naviyat asoslari va huquq ta’limi', 'Milliy g‘oya, ma’naviyat asoslari va huquq ta’limi'), ('Ijtimoiy fanlar', 'Ijtimoiy fanlar'), ('Jismoni madaniyat', 'Jismoni madaniyat'), ('Sport turlarini o‘qitish metodikasi', 'Sport turlarini o‘qitish metodikasi'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Ingliz tili amaliy kursi', 'Ingliz tili amaliy kursi'), ('Fakultetlararo chet tillar', 'Fakultetlararo chet tillar'), ('Rus tili va adabiyoti', 'Rus tili va adabiyoti'), ('Qozoq tili va adabiyoti', 'Qozoq tili va adabiyoti'), ('Umumiy tibbiy fanlar', 'Umumiy tibbiy fanlar')], default=None, max_length=155, verbose_name='Kafedrasi'),
        ),
        migrations.AddField(
            model_name='vote',
            name='tanlov',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professors.tanlov'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vote2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovoz', models.CharField(choices=[('Xa', 'Xa'), ('yoq', 'Yoq'), ('betaraf', 'Betaraf')], max_length=10, verbose_name='Ovoz')),
                ('ilmiy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.ilmiyunvon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ovoz Berish',
                'verbose_name_plural': 'Ovoz Berishlar',
            },
        ),
    ]
