# Generated by Django 5.0.3 on 2024-03-28 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmiyunvon',
            name='voted_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ilmiyunvon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
