# Generated by Django 5.0.3 on 2024-03-28 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_ilmiyunvon_voted_by_user_alter_ilmiyunvon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilmiyunvon',
            name='voted_by_user',
        ),
        migrations.AlterField(
            model_name='ilmiyunvon',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
