# Generated by Django 5.0.3 on 2024-03-27 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_ilmiyunvon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilmiyunvon',
            name='scientific_title',
        ),
        migrations.RemoveField(
            model_name='ilmiyunvon',
            name='user',
        ),
        migrations.AddField(
            model_name='ilmiyunvon',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Ism Familiya sharif'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ilmiyunvon',
            name='unvon',
            field=models.CharField(default=1, max_length=255, verbose_name='Ilmiy Unvon'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_title', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Ilmiy unvon')),
                ('unvon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.ilmiyunvon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.usercreate')),
            ],
            options={
                'verbose_name': 'Ovoz berish',
                'verbose_name_plural': 'Ovoz berish',
            },
        ),
    ]
