# Generated by Django 5.0.3 on 2024-07-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_tanlov_alter_vote_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='ilmiy_unvon',
        ),
    ]
