# Generated by Django 5.0.3 on 2024-07-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_kengash_alter_vote_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Ovoz Berish', 'verbose_name_plural': 'Lavozimga ovoz berishlar'},
        ),
        migrations.AlterModelOptions(
            name='vote2',
            options={'verbose_name': 'Ovoz Berish', 'verbose_name_plural': 'Ilmiy kengash ovozlari'},
        ),
    ]
