# Generated by Django 5.0.3 on 2024-07-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_remove_vote_ilmiy_unvon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilmiyunvon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tanlov',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
