# Generated by Django 5.0.3 on 2024-03-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_remove_ilmiyunvon_scientific_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='scientific_title',
            field=models.CharField(choices=[('Xa', 'Xa'), ("yo'q", "Yo'q"), ('betaraf', 'Betaraf')], default='no', max_length=20, verbose_name='Ilmiy unvon'),
        ),
    ]
