# Generated by Django 5.0.3 on 2024-03-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_remove_ilmiyunvon_voted_by_user_alter_ilmiyunvon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmiyunvon',
            name='unvon_shifr',
            field=models.CharField(default=1, max_length=255, verbose_name='Ilmiy Unvon Shifri'),
            preserve_default=False,
        ),
    ]
