# Generated by Django 5.0.3 on 2024-07-24 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_alter_ilmiyunvon_id_alter_tanlov_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='tanlov',
        ),
        migrations.AddField(
            model_name='vote',
            name='ilmiy_unvon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professors.ilmiyunvon'),
            preserve_default=False,
        ),
    ]
