# Generated by Django 5.0.3 on 2024-07-24 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_remove_vote_tanlov_vote_ilmiy_unvon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='ilmiy_unvon',
        ),
        migrations.AddField(
            model_name='vote',
            name='tanlov',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professors.tanlov'),
            preserve_default=False,
        ),
    ]
