# Generated by Django 5.0.3 on 2024-07-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_ilmiyunvon_voted_by_user_alter_ilmiyunvon_id'),
        ('professors', '0005_alter_ilmiyunvon_kaf'),
    ]

    operations = [
    ]
