# Generated by Django 4.2.11 on 2024-03-29 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professors', '0005_alter_ilmiyunvon_kaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilmiyunvon',
            name='kaf',
            field=models.CharField(choices=[('Umumiy pedagogika va psixologiya', 'Umumiy pedagogika va psixologiya'), ('Maktabgacha ta’lim', 'Maktabgacha ta’lim'), ('Boshlang‘ich ta’lim', 'Boshlang‘ich ta’lim'), ('Pedagogika va psixologiya', 'Pedagogika va psixologiya'), ('Musiqa ta’limi', 'Musiqa ta’limi'), ('Tasviriy san’at va muhandislik grafikasi', 'Tasviriy san’at va muhandislik grafikasi'), ('Biologiya', 'Biologiya'), ('Kimyo', 'Kimyo'), ('Geografiya va iqtisodiy bilim asoslari', 'Geografiya va iqtisodiy bilim asoslari'), ('Matematika', 'Matematika'), ('Informatika', 'Informatika'), ('Fizika va astronomiya', 'Fizika va astronomiya'), ('Texnologik ta’lim', 'Texnologik ta’lim'), ('O‘zbek tilshunosligi', 'O‘zbek tilshunosligi'), ('O‘zbek tili va adabiyoti', 'O‘zbek tili va adabiyoti'), ('Tarix', 'Tarix'), ('Milliy g‘oya, ma’naviyat asoslari va huquq ta’limi', 'Milliy g‘oya, ma’naviyat asoslari va huquq ta’limi'), ('Ijtimoiy fanlar', 'Ijtimoiy fanlar'), ('Jismoni madaniyat', 'Jismoni madaniyat'), ('Sport turlarini o‘qitish metodikasi', 'Sport turlarini o‘qitish metodikasi'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Ingliz tili amaliy kursi', 'Ingliz tili amaliy kursi'), ('Fakultetlararo chet tillar', 'Fakultetlararo chet tillar'), ('Rus tili va adabiyoti', 'Rus tili va adabiyoti'), ('Qozoq tili va adabiyoti', 'Qozoq tili va adabiyoti'), ('Umumiy tibbiy fanlar', 'Umumiy tibbiy fanlar')], default=None, max_length=155, verbose_name='Kafedrasi'),
        ),
        migrations.AlterField(
            model_name='usercreate',
            name='kaf',
            field=models.CharField(choices=[('Umumiy pedagogika va psixologiya', 'Umumiy pedagogika va psixologiya'), ('Maktabgacha ta’lim', 'Maktabgacha ta’lim'), ('Boshlang‘ich ta’lim', 'Boshlang‘ich ta’lim'), ('Pedagogika va psixologiya', 'Pedagogika va psixologiya'), ('Musiqa ta’limi', 'Musiqa ta’limi'), ('Tasviriy san’at va muhandislik grafikasi', 'Tasviriy san’at va muhandislik grafikasi'), ('Biologiya', 'Biologiya'), ('Kimyo', 'Kimyo'), ('Geografiya va iqtisodiy bilim asoslari', 'Geografiya va iqtisodiy bilim asoslari'), ('Matematika', 'Matematika'), ('Informatika', 'Informatika'), ('Fizika va astronomiya', 'Fizika va astronomiya'), ('Texnologik ta’lim', 'Texnologik ta’lim'), ('O‘zbek tilshunosligi', 'O‘zbek tilshunosligi'), ('O‘zbek tili va adabiyoti', 'O‘zbek tili va adabiyoti'), ('Tarix', 'Tarix'), ('Milliy g‘oya, ma’naviyat asoslari va huquq ta’limi', 'Milliy g‘oya, ma’naviyat asoslari va huquq ta’limi'), ('Ijtimoiy fanlar', 'Ijtimoiy fanlar'), ('Jismoni madaniyat', 'Jismoni madaniyat'), ('Sport turlarini o‘qitish metodikasi', 'Sport turlarini o‘qitish metodikasi'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Ingliz tili amaliy kursi', 'Ingliz tili amaliy kursi'), ('Fakultetlararo chet tillar', 'Fakultetlararo chet tillar'), ('Rus tili va adabiyoti', 'Rus tili va adabiyoti'), ('Qozoq tili va adabiyoti', 'Qozoq tili va adabiyoti'), ('Umumiy tibbiy fanlar', 'Umumiy tibbiy fanlar')], default=None, max_length=155, verbose_name='Kafedrasi'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='scientific_title',
            field=models.CharField(choices=[('Xa', 'Xa'), ('yoq', 'Yoq'), ('betaraf', 'Betaraf')], default='betaraf', max_length=20, verbose_name="O'z ovozingini tanlang"),
        ),
        migrations.AlterField(
            model_name='vote',
            name='unvon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.ilmiyunvon', verbose_name='Saylanuvchi'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi ismi'),
        ),
    ]
