# Generated by Django 5.0.3 on 2024-03-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_alter_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmiyunvon',
            name='voted_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
