# Generated by Django 5.0.3 on 2024-07-24 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_remove_vote_ilmiy_unvon_vote_tanlov'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='ilmiy_unvon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professors.ilmiyunvon'),
            preserve_default=False,
        ),
    ]
