# Generated by Django 5.0.3 on 2024-07-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0007_vote_ilmiy_unvon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='ilmiy_unvon',
        ),
    ]
