# Generated by Django 5.0.3 on 2024-07-23 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0007_remove_ilmiyunvon_voted_by_user_alter_ilmiyunvon_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanlov',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Ism Familiya sharif')),
                ('kaf', models.CharField(choices=[('Metematika - Informatika', 'Matematika - Informatika'), ('Fizika', 'Fizika'), ("Sana'tshunoslik", "Sana'tshunoslik"), ('Jismoniy madaniyat', 'Jismoniy madaniyat'), ('Tabiy fanlar', 'Tabiy fanlar'), ('Ingliz tili va adabiyoti', 'Ingliz tili va adabiyoti'), ('Rus tili va Qozoq tillari filialogiyasi', 'Rus tili va Qozoq tillari filialogiyasi'), ('Tibbiyot', 'Tibbiyot'), ("Maktabgacha va boshlang'ich ta'lim", "Maktabgacha va boshlang'ich ta'lim"), ('Tarix', 'Tarix'), ('O‘zbek tili va adabiyoti fakulteti', 'O‘zbek tili va adabiyoti fakulteti')], default=None, max_length=155, verbose_name='Kafedrasi')),
                ('scientific_title', models.CharField(choices=[('kafedra mudiri', 'kafedra mudiri'), ('kafedra professori', 'kafedra professori'), ('kafedra dotsenti', 'kafedra dotsenti'), ('kafedra katta o‘qituvchisi', 'kafedra katta o‘qituvchisi'), ('kafedra o‘qituvchisi lavozimi', 'kafedra o‘qituvchisi lavozimi')], max_length=255, verbose_name='Lavozimni tanlang')),
            ],
            options={
                'verbose_name': 'Ilmiy Unvon',
                'verbose_name_plural': 'Ilmiy Unvonlar',
            },
        ),
    ]
