# Generated by Django 5.0.3 on 2024-07-23 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0008_tanlov'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tanlov',
            options={'verbose_name': 'Tanlov', 'verbose_name_plural': 'Tanlovlar'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Ovoz Berish', 'verbose_name_plural': 'Ovoz Berishlar'},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='scientific_title',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='unvon',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='vote',
            name='ilmiy_unvon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professors.ilmiyunvon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='ovoz',
            field=models.CharField(choices=[('Xa', 'Xa'), ('yoq', 'Yoq'), ('betaraf', 'Betaraf')], default=1, max_length=10, verbose_name='Ovoz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='tanlov',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='professors.tanlov'),
            preserve_default=False,
        ),
    ]
