# Generated by Django 5.0.3 on 2024-07-24 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0009_vote_ilmiy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='ilmiy',
        ),
        migrations.CreateModel(
            name='Vote2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovoz', models.CharField(choices=[('Xa', 'Xa'), ('yoq', 'Yoq'), ('betaraf', 'Betaraf')], max_length=10, verbose_name='Ovoz')),
                ('ilmiy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.ilmiyunvon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ovoz Berish',
                'verbose_name_plural': 'Ovoz Berishlar',
            },
        ),
    ]
